# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript



trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CmdLine@2
  inputs:
    script: |
      echo Write your commands here
      git clone https://github.com/samirans89/karma-browserstack-launcher.git
      echo $(Build.SourcesDirectory)
      pwd
      ls
      echo Hello world
    workingDirectory: '$(Build.SourcesDirectory)'/..
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm test
  displayName: 'npm install and test'
